import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import Navbar from "../components/Shared/Navber";
import Footer from "../components/Shared/Footer";
import "./globals.css";

// Space Grotesk 600
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space",
});

// Geist fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="bg-[#181010] text-white">
        {/* Navbar is here */}
        <Navbar />

        {/* Page content */}
        <main className="">{children}</main> {/* pt-20 avoids content being under Navbar */}

        {/* Footer is here */}
        <Footer />
      </body>
    </html>
  );
}
